//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriyatnyyShelest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class PriyatnyyShelestDbEntities1 : DbContext
    {
        public PriyatnyyShelestDbEntities1()
            : base("name=PriyatnyyShelestDbEntities1")
        {

        }

        public static PriyatnyyShelestDbEntities1 _context;

        public static PriyatnyyShelestDbEntities1 GetContext()
        {
        if (_context is null)
            _context = new PriyatnyyShelestDbEntities1();   
        return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agents> Agents { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductSale> ProductSale { get; set; }
        public virtual DbSet<VW_AgentDetails> VW_AgentDetails { get; set; }
    }
}
